"""Render a Digest as a Markdown file under data/digests/YYYY-MM-DD.md."""

from __future__ import annotations

from pathlib import Path

from ..lib.paths import digests_dir
from ..lib.types import ClassifiedItem, Digest, HookFormat, PostHook


SOURCE_BADGES: dict[str, str] = {
    "hn": "HN",
    "reddit": "Reddit",
    "github": "GitHub",
    "devto": "Dev.to",
    "hf": "HF",
    "newsletter": "Newsletter",
    "x": "X",
    "other": "Other",
}

WEDGE_LABELS: dict[str, str] = {
    "cold_start": "cold-start",
    "markup": "0% markup",
    "self_host": "self-host",
    "mcp": "MCP",
    "reliability": "reliability",
    "other": "other",
}

FORMAT_HEADINGS: dict[HookFormat, str] = {
    "x_thread": "X thread opener",
    "linkedin": "LinkedIn opener",
    "reddit": "Reddit post title",
    "hn_comment": "HN comment seed",
    "devto_title": "Dev.to title",
}


def render(digest: Digest) -> str:
    """Render the digest as a Markdown string."""

    parts: list[str] = []
    parts.append(f"# Routr Daily Signal Digest — {digest.date}\n")

    # Source counts at the top so we can spot dead sources quickly.
    if digest.source_counts:
        bits = ", ".join(f"`{k}`: {v}" for k, v in digest.source_counts.items())
        parts.append(f"**Source counts:** {bits}\n")

    if digest.notes:
        parts.append("**Notes:** " + "; ".join(digest.notes) + "\n")

    parts.append("\n## 🔴 Top pain signals\n")
    if not digest.pain_signals:
        parts.append("_No relevant pain signals today._\n")
    else:
        for i, c in enumerate(digest.pain_signals, start=1):
            parts.append(_render_signal(i, c))

    parts.append("\n## 📈 Active accounts (engage early)\n")
    if not digest.active_accounts:
        parts.append("_No new accounts surfaced today._\n")
    else:
        for lead in digest.active_accounts:
            url = lead.profile_url or ""
            url_part = f" — [{url}]({url})" if url else ""
            parts.append(
                f"- **{_badge(lead.platform)}** `@{lead.handle}`{url_part}\n"
                f"  - Pain: {lead.pain_in_their_words}\n"
                f"  - Angle: {lead.pitch_angle}\n"
            )

    parts.append("\n## ✍️ Pre-drafted post hooks\n")
    if not digest.hooks:
        parts.append("_No drafts produced today._\n")
    else:
        # Build the signal_id -> url map once so each hook can include
        # a clickable link to the source.
        signal_urls: dict[str, str] = {
            c.raw.id: c.raw.url for c in digest.pain_signals if c.raw.url
        }
        for hook in digest.hooks:
            parts.append(_render_hook(hook, signal_urls=signal_urls))

    parts.append(
        "\n---\n"
        "_Generated by `routr-signal-engine`. "
        "Edit prompts under `config/prompts/` to change the tone or scoring rubric._\n"
    )
    return "".join(parts)


def write_to_disk(digest: Digest) -> Path:
    path = digests_dir() / f"{digest.date}.md"
    path.write_text(render(digest), encoding="utf-8")
    return path


def _render_signal(idx: int, c: ClassifiedItem) -> str:
    badge = _badge(c.raw.source)
    wedge = WEDGE_LABELS.get(c.wedge, c.wedge)
    topics = c.raw.extra.get("topics") or []
    topic_str = ", ".join(topics[:3]) if topics else wedge
    score_str = f"llm {c.score:.2f} · cos {c.cosine_score:.2f} · comb {c.combined_score:.2f}"
    author = f" by `@{c.raw.author}`" if c.raw.author else ""
    title = c.raw.title.strip() or "(no title)"
    body_lines: list[str] = []
    snapshot = c.raw.extra.get("person_snapshot")
    if snapshot and snapshot != "unknown":
        body_lines.append(f"  - Who: {snapshot}")
    if c.pain_summary:
        body_lines.append(f"  - Pain: {c.pain_summary}")
    if c.suggested_angle:
        body_lines.append(f"  - Angle: {c.suggested_angle}")
    body_lines.append(f"  - Link: {c.raw.url}")
    body = "\n".join(body_lines)

    return (
        f"{idx}. **[{badge}]** `{topic_str}` ({score_str}){author} — {title}\n{body}\n\n"
    )


def _render_hook(hook: PostHook, signal_urls: dict[str, str] | None = None) -> str:
    heading = FORMAT_HEADINGS.get(hook.format, hook.format)
    anchor = hook.anchor_signal_id
    anchor_suffix = ""
    source_line = ""
    if anchor:
        anchor_suffix = f" _(anchored to {anchor})_"
        if signal_urls and anchor in signal_urls:
            source_line = f"\n[source]({signal_urls[anchor]})\n"
    return f"### {heading}{anchor_suffix}\n\n{hook.text}\n{source_line}\n"


def _badge(source: str) -> str:
    return SOURCE_BADGES.get(source, source)
